version: '3.1'

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "hackme"
      POSTGRES_DB: "db1"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data


volumes:
  postgresql_data:
